name: ChestSort
version: 0.1.0
author: Smarticles101
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
main: me\logans\ChestSort\Main

commands:
  sort:
    description: Touch a chest and it will be sorted!
    useage: /sort
    aliases: [s]
